mysite/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from myapp.views import delete, edit, index,get_student,create
from todo.views import todolist,delete_task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('student/<slug:slug>',get_student,name='student'),
    path('create/',create,name='create'),
    path('edit/<int:pk>',edit,name='edit'),
    path('delete/<int:pk>',delete,name='delete'),
    path('todo/',todolist,name='todo'),
    path('todo/delete/<int:pk>',delete_task,name='todo_delete'),
]

base/models.py
from django.db import models

# Create your models here.

myapp/models.py
from statistics import mode
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

class Section(models.Model):
    sect=models.CharField(blank=True,max_length=100,default='cse')

    def __str__(self):
        return self.sect

class Student(models.Model):
    name=models.CharField(max_length=200,default=0)
    father=models.CharField(max_length=200,default='my_father')
    slug=models.SlugField(blank=True)
    s=models.ForeignKey(Section,null=True,on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def save(self):
        self.slug=slugify(self.name)
        super(Student,self).save()

    def get_absolute_url(self):
        return reverse('student',args=[str(self.slug)])

todo/models.py
from django.db import models

# Create your models here.

class task(models.Model):
    task_text=models.CharField(max_length=500,default="task")

    def __str__(self):
        return self.task_text

    def save(self):
        super(task,self).save()

myapp/forms.py
from dataclasses import fields
from operator import mod
from django import forms
from myapp import models

class Add(forms.ModelForm):
    class Meta:
        model=models.Student
        fields=['name','s']

todo/forms.py
from email.policy import default
from statistics import mode
from todo.models import task
from django import forms

class input_task(forms.ModelForm):
    task_text=forms.CharField(max_length=500, widget=forms.TextInput(attrs={'class': "form-input"}))
    class Meta:
        model=task
        fields=['task_text']

base/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from myapp.models import Student
from myapp.forms import Add

# Create your views here.

def index(request):
    want=request.GET.get('q',None)
    if not want:
        details=Student.objects.all()
    else:
        details=Student.objects.filter(name__contains=want)
    return render(request,'myapp/index.html',{'details':details})

def get_student(request,slug=None):
    st=get_object_or_404(Student,slug=slug)
    return render(request,'myapp/stu.html',{'st':st})

def create(request):
    if request.method=='POST':
        form=Add(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            form=Add()
    else:
        form=Add()
    return render(request,'myapp/new.html',{'form':form})

def edit(request,pk=None):
    stu=get_object_or_404(Student,pk=pk)
    if(request.method=='POST'):
        form=Add(request.POST,instance=stu)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form=Add()
    return render(request,'myapp/edit.html',{'form':form})

def delete(request,pk=None):
    stu=get_object_or_404(Student,pk=pk)
    if stu:
        stu.delete()
    return HttpResponse("Deleted "+stu.name+" Succesfully")

todo/views.py
import re
from django.shortcuts import redirect, render,get_object_or_404
from django.urls import is_valid_path
from todo.forms import input_task
from todo.models import task

# Create your views here.

def todolist(request):
    if request.method=='POST':
        form=input_task(request.POST)
        if form.is_valid:
            form.save()
        else:
            form=input_task()
    else:
        form=input_task()
    tasklu=task.objects.all()
    return render(request,'todo.html',{'form':input_task,'tasks':tasklu})

def delete_task(request,pk=None):
    if pk:
        tas=get_object_or_404(task,pk=pk)
        tas.delete()
    return redirect('/todo')

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'create' %}">Add a Student</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'todo' %}">To-do List</a></li>
        </ul>
    </nav>
    <div class="container container-border">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

myapp/templates/myapp/edit.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <form action="" method="POST" class="form">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="form-control btn btn-primary block">
    </form>
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'base/base.html' %}
{% block content %}
<form action="/" method="get" class="form-inline">
    <input type="text" id="q" name="q" class="form-control" placeholder="search a student">
    <input type="submit" class="form-control btn btn-primary">
</form>
{% for student in details %}
<div class="card">
    <div class="card-body">
        <h2 class="card-title"><a href="{% url 'student' student.slug %}">{{student.name}}</a></h2>
        <p class="card-text">{{student.father}}</p>
        <a class="btn btn-warning" href="{% url 'edit' pk=student.pk %}">Change</a>
        <a class="btn btn-danger" href="{% url 'delete' pk=student.pk %}">Delete</a>
    </div>
</div>
{% endfor %}
{% endblock %}

myapp/templates/myapp/new.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <form action="" method="POST" class="form">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="form-control btn btn-primary block">
    </form>
</div>
{% endblock %}

myapp/templates/myapp/stu.html
{% extends 'base/base.html' %}
{% block content %}
<div class="card">
    <div class="card-body">
        <h2 class="card-title">{{st.name}}</h2>
        <p class="card-text">{{st.father}}</p>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h2>Other Students from this {{st.s}} are:</h2>
            {% for s_stu in st.s.student_set.all %}
            <p>{{s_stu}}</p>
        {% endfor %}
    </div>

</div>
{% endblock %}

todo/templates/todo.html
{% extends 'base/base.html' %}
{% block content %}
<h1>To do</h1>
<form class="" action="" method="POST">
    {% csrf_token %}
    <div class="row p-2">
        {{form}}
        <input type="submit" value="Add" class="btn btn-primary">
    </div>
</form>
<ul class="list-group">
{% for task in tasks %}
    <li class="list-group-item justify-content-between d-flex h4">{{task}}<a href="{% url 'todo_delete' pk=task.pk %}" type="button"  class="btn btn-danger">Delete</a></li>
{% endfor %}
</ul>
{% endblock %}